import React from "react";

const CompanyOptions = ({ handleCompanyChange }) => (
  <div>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="HP"
        onChange={handleCompanyChange}
      />
      HP
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="MSI"
        onChange={handleCompanyChange}
      />
      MSI
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="MI"
        onChange={handleCompanyChange}
      />
      MI
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="Razer"
        onChange={handleCompanyChange}
      />
      Razer
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="Apple"
        onChange={handleCompanyChange}
      />
      Apple
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="Acer"
        onChange={handleCompanyChange}
      />
      Acer
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="Dell"
        onChange={handleCompanyChange}
      />
      Dell
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="Lenovo"
        onChange={handleCompanyChange}
      />
      Lenovo
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="LG"
        onChange={handleCompanyChange}
      />
      LG
    </label>
    <label>
      <input
        type="radio"
        name="companyOption"
        value="ASUS"
        onChange={handleCompanyChange}
      />
      ASUS
    </label>
  </div>
);

export default CompanyOptions;
